#!/bin/bash


#
# Variables for path
#

SPDK_DIR=${ROOT_DIR}/spdk


#
# Variables for SPDK configuration
#

SPDK_VERSION=23.01.1


#
# Variables for ZNS
#

NVME_ID=nvme0
NVME_NSID=1

# Specific zoned namespace of NVMe SSD
ZNS_NAME=${NVME_ID}n${NVME_NSID}
